[package]
name = "csv_to_json"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
csv = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
